export const CONTENT_FETCHING = "CONTENT_FETCHING";
export const CONTENT_FULFILLED = "CONTENT_FULFILLED";
export const CONTENT_REJECTED = "CONTENT_REJECTED";
export const SET_MESSAGE = "SET_MESSAGE";
